version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports: 
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=bruna
      - POSTGRESQL_PASSWORD=123
      - POSTGRESQL_DATABASE=googleLogin
